services:
  mongo2: # Réplica de la base de datos
    image: mongo:7.0
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017" # En Windows será el 27017 nativo
    volumes:
      - ./data/mongo2:/data/db

  storage-node-2:
    build: ./services/storage-node
    container_name: storage-node-2
    ports:
      - "50052:50052" # Fíjate que cambiamos el puerto para que no choque
    environment:
      - NODE_ID=storage-node-2
      - PORT=50052
      - TAILSCALE_IP=${MY_TAILSCALE_IP} # La IP de Tailscale de esta PC Windows
      - METADATA_HOST=${METADATA_HOST} # La IP de Tailscale de Fedora
    volumes:
      - ./data/storage2:/app/uploads
      - ./proto:/app/proto:ro

  storage-node-3:
    build: ./services/storage-node
    container_name: storage-node-3
    ports:
      - "50053:50053" # Siguiente puerto disponible
    environment:
      - NODE_ID=storage-node-3
      - PORT=50053
      - TAILSCALE_IP=${MY_TAILSCALE_IP}
      - METADATA_HOST=${METADATA_HOST}
    volumes:
      - ./data/storage3:/app/uploads
      - ./proto:/app/proto:ro

  storage-node-4:
    build: ./services/storage-node
    container_name: storage-node-4
    ports:
      - "50054:50054" # Siguiente puerto disponible
    environment:
      - NODE_ID=storage-node-4
      - PORT=50054
      - TAILSCALE_IP=${MY_TAILSCALE_IP}
      - METADATA_HOST=${METADATA_HOST}
    volumes:
      - ./data/storage4:/app/uploads
      - ./proto:/app/proto:ro